# Generated by Django 4.2.3 on 2023-07-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdb',
            name='date',
            field=models.DateField(max_length=70, null=True),
        ),
    ]
